name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup dependencies
      run: |
        apt install neovim luarocks

    - name: Run tests
      run: |
        ./run_tests_busted.sh tests/notify.lua tests/status.lua
