name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup dependencies
      run: |
        sudo apt update
        sudo apt install --yes neovim luarocks

    - name: Run tests
      run: |
        luarocks init
        luarocks test
